### PR TITLE
for-upstream/various-refactor

### PR DESCRIPTION
**Pull request by matthewk-xilinx**
This PR encapsulates various refactoring that went on before one of our other main feature additions.
There's not much here in terms of new features, it's all about streamlining modules (mostly main.py) to make them easier to add things to in the next PRs.

The only functional changes should be the renaming of the pcap file to match the json filename and the restriction of the solver to QF_UFBV, which we haven't observed to have any detrimental effects in practice (just a performance increase).

### CODE REVIEW

**Comment by jafingerhut** [comment]
Looks like one test fails because it still needs to call some renamed functions?  These changes in my local copy enable that last test to pass:
```
--- a/tests/check_system.py
+++ b/tests/check_system.py
@@ -399,9 +399,9 @@ class CheckSystem:
         # This test case checks that we do not attempt to advance beyond the
         # last element of a header stack.
 
-        Config().load_test_defaults()
+        load_test_config()
 
-        results = process_json_file('examples/parser-cycle.json')
+        results = generate_test_cases('examples/parser-cycle.json')
         expected_results = {
             ('start', 'sink', (u'tbl_parsercycle37', u'parsercycle37')):
```

**Comment by jfingerh** [comment]
If you have anywhere in your plans the thought of transitioning this code to use Python3.x instead of Ptyhon2.7, the open source P4 tools have recently seen some activity in updating them in that direction, too.  I intend absolutely _no pressure_ by mentioning this -- I know it can be a pain to test such changes completely and be confident one has not missed anything.

**Comment by matthewk-xilinx** [comment]
> Python3.x instead of Python2.7
We'd just finished working on a set of features in our internal repo when we noticed that p4c etc no longer support Python2.  I expect that when we next have a set of work to do updating to Python3 will be part of it.  For now we're just keeping the tests running with slightly older versions in our internal repo.  
(related: After putting this up I realised I didn't have a way of running the tests in this repo anymore, so I've been getting that going this morning.)

**Comment by matthewk-xilinx** [comment]
Got the tests working.  Looks like your proposed fix was all that was needed.  I think some commits had gotten re-ordered and introduced that problem.

**Comment by jafingerhut** [comment]
Thanks for updating the Travis script -- that got the tests passing, and seems to me a perfectly reasonable approach to take here.

**Review by jafingerhut — APPROVED** [review]
These changes are a bit long for me to review with a fine-toothed comb, but given that the tests are passing, and that you are driving development forward, I say go ahead.

**Pull request merged**
